import { ALL_PERMISSION_KEYS, PERMISSION_KEYS } from './permissions';

export interface SystemRoleDefinition {
  name: string;
  description: string;
  permissions: string[];
}

/**
 * System roles (company_id = NULL) seeded once, shared by every tenant.
 */
export const SYSTEM_ROLES: SystemRoleDefinition[] = [
  {
    name: 'Owner',
    description: 'صاحب المنشأة - كل الصلاحيات',
    permissions: ALL_PERMISSION_KEYS,
  },
  {
    name: 'Manager',
    description: 'مدير فرع - إدارة تشغيلية دون التحكم بالتكاملات أو صلاحيات المستخدمين',
    permissions: [
      PERMISSION_KEYS.IAM_ROLES_VIEW,
      PERMISSION_KEYS.IAM_USERS_VIEW,
      PERMISSION_KEYS.TENANCY_BRANCHES_VIEW,
      PERMISSION_KEYS.TENANCY_WAREHOUSES_VIEW,
      PERMISSION_KEYS.TENANCY_WAREHOUSES_MANAGE,
      PERMISSION_KEYS.TENANCY_POS_DEVICES_VIEW,
      PERMISSION_KEYS.TENANCY_POS_DEVICES_MANAGE,
      PERMISSION_KEYS.PRODUCTS_READ,
      PERMISSION_KEYS.PRODUCTS_CREATE,
      PERMISSION_KEYS.PRODUCTS_UPDATE,
      PERMISSION_KEYS.PRODUCTS_DELETE,
      PERMISSION_KEYS.INVENTORY_READ,
      PERMISSION_KEYS.INVENTORY_ADJUST,
      PERMISSION_KEYS.INVENTORY_COUNT,
      PERMISSION_KEYS.INVENTORY_TRANSFER,
      PERMISSION_KEYS.CUSTOMERS_READ,
      PERMISSION_KEYS.CUSTOMERS_CREATE,
      PERMISSION_KEYS.CUSTOMERS_UPDATE,
      PERMISSION_KEYS.CUSTOMERS_DELETE,
      PERMISSION_KEYS.SUPPLIERS_READ,
      PERMISSION_KEYS.SUPPLIERS_CREATE,
      PERMISSION_KEYS.SUPPLIERS_UPDATE,
      PERMISSION_KEYS.SUPPLIERS_DELETE,
      PERMISSION_KEYS.SALES_READ,
      PERMISSION_KEYS.SALES_CREATE,
      PERMISSION_KEYS.SALES_CANCEL,
      PERMISSION_KEYS.SALES_PAYMENT_RECORD,
      PERMISSION_KEYS.SALES_RETURN,
      PERMISSION_KEYS.INVOICES_READ,
      PERMISSION_KEYS.PURCHASES_READ,
      PERMISSION_KEYS.PURCHASES_CREATE,
      PERMISSION_KEYS.PURCHASES_CANCEL,
      PERMISSION_KEYS.PURCHASES_PAYMENT_RECORD,
      PERMISSION_KEYS.PURCHASES_RETURN,
      PERMISSION_KEYS.EXPENSES_READ,
      PERMISSION_KEYS.EXPENSES_CREATE,
      PERMISSION_KEYS.EXPENSES_UPDATE,
      PERMISSION_KEYS.EXPENSES_DELETE,
      PERMISSION_KEYS.ACCOUNTING_READ,
      PERMISSION_KEYS.ACCOUNTING_REPORTS_VIEW,
      PERMISSION_KEYS.ACCOUNTING_AR_VIEW,
      PERMISSION_KEYS.ACCOUNTING_AP_VIEW,
      PERMISSION_KEYS.IMPORT_READ,
      PERMISSION_KEYS.IMPORT_CREATE,
    ],
  },
  {
    name: 'Cashier',
    description: 'كاشير - يشغّل نقطة البيع؛ لا يملك إلغاء بيع مكتمل (صلاحية مشرف)',
    permissions: [
      PERMISSION_KEYS.PRODUCTS_READ,
      PERMISSION_KEYS.CUSTOMERS_READ,
      PERMISSION_KEYS.SALES_READ,
      PERMISSION_KEYS.SALES_CREATE,
      PERMISSION_KEYS.SALES_PAYMENT_RECORD,
      PERMISSION_KEYS.INVOICES_READ,
      // The POS screen loads the warehouse list on open (to know which
      // warehouse's stock to sell from) - without this a Cashier, whose
      // entire job is running POS, can't even open the page.
      PERMISSION_KEYS.TENANCY_WAREHOUSES_VIEW,
    ],
  },
  {
    name: 'Accountant',
    description:
      'محاسب - يدير دليل الحسابات والمصروفات، ويرى المبيعات/المشتريات/الفواتير للتقارير؛ لا يُنشئ مبيعات أو مشتريات بنفسه (فصل مهام)',
    permissions: [
      PERMISSION_KEYS.AUDIT_VIEW,
      PERMISSION_KEYS.PRODUCTS_READ,
      PERMISSION_KEYS.INVENTORY_READ,
      PERMISSION_KEYS.CUSTOMERS_READ,
      PERMISSION_KEYS.SUPPLIERS_READ,
      PERMISSION_KEYS.SALES_READ,
      PERMISSION_KEYS.INVOICES_READ,
      PERMISSION_KEYS.PURCHASES_READ,
      PERMISSION_KEYS.PURCHASES_PAYMENT_RECORD,
      PERMISSION_KEYS.EXPENSES_READ,
      PERMISSION_KEYS.EXPENSES_CREATE,
      PERMISSION_KEYS.EXPENSES_UPDATE,
      PERMISSION_KEYS.EXPENSES_DELETE,
      PERMISSION_KEYS.ACCOUNTING_READ,
      PERMISSION_KEYS.ACCOUNTING_MANAGE,
      PERMISSION_KEYS.ACCOUNTING_REPORTS_VIEW,
      PERMISSION_KEYS.ACCOUNTING_AR_VIEW,
      PERMISSION_KEYS.ACCOUNTING_AP_VIEW,
      PERMISSION_KEYS.ACCOUNTING_OPENING_BALANCE_MANAGE,
      PERMISSION_KEYS.ACCOUNTING_PERIOD_MANAGE,
      PERMISSION_KEYS.ACCOUNTING_RECONCILIATION_MANAGE,
      PERMISSION_KEYS.IMPORT_READ,
    ],
  },
  {
    name: 'Inventory Manager',
    description: 'مسؤول المخزون - صلاحيات المخزون والمنتجات والمشتريات (استلام المخزون) الكاملة',
    permissions: [
      PERMISSION_KEYS.TENANCY_WAREHOUSES_VIEW,
      PERMISSION_KEYS.PRODUCTS_READ,
      PERMISSION_KEYS.PRODUCTS_CREATE,
      PERMISSION_KEYS.PRODUCTS_UPDATE,
      PERMISSION_KEYS.INVENTORY_READ,
      PERMISSION_KEYS.INVENTORY_ADJUST,
      PERMISSION_KEYS.INVENTORY_COUNT,
      PERMISSION_KEYS.INVENTORY_TRANSFER,
      PERMISSION_KEYS.SUPPLIERS_READ,
      PERMISSION_KEYS.PURCHASES_READ,
      PERMISSION_KEYS.PURCHASES_CREATE,
      PERMISSION_KEYS.PURCHASES_RETURN,
      PERMISSION_KEYS.IMPORT_READ,
      PERMISSION_KEYS.IMPORT_CREATE,
    ],
  },
  {
    name: 'Integration',
    description:
      'دور نظامي غير قابل لتسجيل الدخول - يُسنَد فقط للعضوية النظامية التي تمثّل ' +
      'تكامل قيّدها داخل هذه المنشأة (docs/QEEDHA_INTEGRATION.md "System actor"). ' +
      'أضيق ما يلزم فعليًا للتدفق الحالي: حل/إنشاء عملاء، قراءة المبيعات لأغراض ' +
      'البحث عن الفاتورة، وتسوية دفعة على بيع قائم - لا شيء آخر.',
    permissions: [
      PERMISSION_KEYS.CUSTOMERS_READ,
      PERMISSION_KEYS.CUSTOMERS_CREATE,
      PERMISSION_KEYS.SALES_READ,
      PERMISSION_KEYS.SALES_PAYMENT_RECORD,
    ],
  },
];
